[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Allow Firebase environment variables to be exposed in client build
[context.production.environment]
  VITE_FIREBASE_EXPOSE_IN_BUILD = "true"