[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npm ci && npm run build"

### Ignore Env Secrets
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "vite.config.js,.env"
